### ISSUE TITLE
Pick up more name pairs, e.g. `long,lat`

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-cluster-map#39]
There's no reason this tool couldn't be smarter at spotting potential latitude/longitude column pairs - since they come in pairs, there's not much risk of seeing a `lat` column and triggering when there's no sensible `lon` to accompany it.

**Comment by simonw** [comment]
Came up in office hours. Let's go for:

- `lon`, `long`, `lng` for longitude
- `lat` for latitude

**Comment by simonw** [comment]
Suggestion: look for these as `_latitude`, `_longitude` style pairs too.

Basically it should kick in if it looks like there are only two columns that could be representing locations in latitude/longitude format.

**Comment by mroswell** [comment]
what happens if the fields appear in a sqlite database converted from geojson, and the the datasette-geojson-map plugin is installed?

**Comment by simonw** [comment]
This won't solve the conflicting problem where two plugins want to display a map at the same time - that's going to have to come later, maybe after the Datasette 1.0 release.

**Comment by simonw** [comment]
I have a power plants table with these columns:

`['rowid', 'country', 'country_long', 'name', 'gppd_idnr', 'capacity_mw', 'latitude', 'longitude', 'primary_fuel', 'other_fuel1', 'other_fuel2', 'other_fuel3', 'commissioning_year', 'owner', 'source', 'url', 'geolocation_source', 'wepp_id', 'year_of_capacity_data', 'generation_gwh_2013', 'generation_gwh_2014', 'generation_gwh_2015', 'generation_gwh_2016', 'generation_gwh_2017', 'generation_data_source', 'estimated_generation_gwh']`

This did NOT display a map... because of my logic that says that if there are multiple ambiguous lat/lon columns it should ignore them.

It thought that `country_long` and `longitude` were rival columns!

I might need some kind of priority mechanism here, such that `country_long` is ignored if there were exact matches for `latitude` and `longitude`. Not sure how best to do that.

**Comment by simonw** [comment]
My current tests look like this:
```python
@pytest.mark.parametrize(
    "input,expected",
    (
        ([], []),
        (["a", "b"], []),
        (["a", "b", "latitude", "longitude"], ["latitude", "longitude"]),
        (["a", "b", "lat", "lon", "c"], ["lat", "lon"]),
        (["a", "b", "lat", "lng", "c"], ["lat", "lng"]),
        (["a", "b", "lat", "long", "c"], ["lat", "long"]),
        # Returns [] because there are multiple potential options:
        (["a", "lat", "lon", "c", "latitude", "longitude"], []),
        # Wildcard matches
        (["a", "foo_latitude", "foo_longitude"], ["foo_latitude", "foo_longitude"]),
        (["a", "foo_latitude", "bar_longitude"], ["foo_latitude", "bar_longitude"]),
        (["a", "foo_lat", "foo_long"], ["foo_lat", "foo_long"]),
        (["a", "foo_lat", "foo_lon"], ["foo_lat", "foo_lon"]),
        (["a", "foo_lat", "foo_lng"], ["foo_lat", "foo_lng"]),
    ),
)
def test_location_columns_from_columns(input, expected):
    actual = location_columns_from_columns(input)
    actual_cap = location_columns_from_columns([col.upper() for col in input])
    assert actual == expected
    assert actual_cap == [col.upper() for col in expected]
```

**Comment by simonw** [comment]
I'm going to say that the prefixes have to match. That should fix the `country_long` problem.

**Comment by simonw** [comment]
Made myself a test database like this:

```bash
echo '[
    {
        "name": "San Francisco",
        "lat": 37.7749,
        "lon": -122.4194
    },
    {
        "name": "New York",
        "lat": 40.7128,
        "lon": -74.006
    },
    {
        "name": "Cleveland",
        "lat": 41.4993,
        "lon": -81.6944
    }
]' | sqlite-utils insert strange.db latlon -
echo '[
    {
        "name": "San Francisco",
        "lat": 37.7749,
        "lng": -122.4194
    },
    {
        "name": "New York",
        "lat": 40.7128,
        "lng": -74.006
    },
    {
        "name": "Cleveland",
        "lat": 41.4993,
        "lng": -81.6944
    }
]' | sqlite-utils insert strange.db latlng -
echo '[
    {
        "name": "San Francisco",
        "lat": 37.7749,
        "long": -122.4194
    },
    {
        "name": "New York",
        "lat": 40.7128,
        "long": -74.006
    },
    {
        "name": "Cleveland",
        "lat": 41.4993,
        "long": -81.6944
    }
]' | sqlite-utils insert strange.db latlong -
echo '[
    {
        "name": "San Francisco",
        "location_lat": 37.7749,
        "location_lng": -122.4194
    },
    {
        "name": "New York",
        "location_lat": 40.7128,
        "location_lng": -74.006
    },
    {
        "name": "Cleveland",
        "location_lat": 41.4993,
        "location_lng": -81.6944
    }
]' | sqlite-utils insert strange.db location -
```
All four tables look like this:

![CleanShot 2024-01-12 at 21 34 16@2x](https://github.com/simonw/datasette-cluster-map/assets/9599/97ce2dc3-f28b-4e50-8481-1818c6a64263)
