### ISSUE TITLE
Make tile server configurable

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-cluster-map#5]
Add a plugin setting to allow configuration of alternative tile servers.

**Comment by simonw** [comment]
Using this:
```json
{
    "plugins": {
        "datasette-cluster-map": {
            "tile_layer": "https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.{ext}",
            "tile_layer_options": {
                "attribution": "Map tiles by <a href=\"http://stamen.com\">Stamen Design</a>, <a href=\"http://creativecommons.org/licenses/by/3.0\">CC BY 3.0</a> &mdash; Map data &copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors",
                "subdomains": "abcd",
                "minZoom": 1,
                "maxZoom": 16,
                "ext": "jpg"
            }
        }
    }
}
```
<img width="914" alt="global-power-plants__global-power-plants__29_684_rows" src="https://user-images.githubusercontent.com/9599/90217628-b47b7e80-ddb6-11ea-99c8-333278d569ab.png">

**Comment by Kabouik** [comment]
This is a great feature, thank you for adding it.

Is there a way to list several tile providers and switch between them with a button? With some data, especially data related to landscapes and topographic features, it is often necessary to switch between layers repeatedly to understand points, _e.g._ between base map, terrain with hillshade, and satellite views. I don't know Python and never used Leaflet directly in Python, but I know the R package for Leaflet supports that (see example below), so I assume it's supported upstream and could be added relatively easily to datasette-cluster-map?

```R
map <- leaflet() %>% 
  addTiles(group = "Map", urlTemplate = mapboxmpa,
           attribution = '© <a href="https://www.mapbox.com/map-feedback/">Mapbox</a> © <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> <strong><a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a></strong>') %>% 
  addTiles(group = "Satellite", urlTemplate = mapboxsat,
           attribution = '© <a href="https://www.mapbox.com/map-feedback/">Mapbox</a> © <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> <strong><a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a></strong>') %>%
  setView(8.750000, 42.566667, zoom = 5)
```

![ss-2021-02-19_100208](https://user-images.githubusercontent.com/7107523/108482300-3a5e1200-7291-11eb-892e-ee06c0230895.png)
